<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="urn:event-ticketing:seat:v1"
                  targetNamespace="urn:event-ticketing:seat:v1">
  <wsdl:documentation>Canonical Seat Inventory SOAP contract. Calls require a Bearer service JWT and propagate correlationId and traceparent through RequestContext.</wsdl:documentation>
  <wsdl:types>
    <xs:schema><xs:import namespace="urn:event-ticketing:seat:v1" schemaLocation="seat-inventory.xsd"/></xs:schema>
  </wsdl:types>
  <wsdl:message name="GetSeatMapInput"><wsdl:part name="parameters" element="tns:GetSeatMapRequest"/></wsdl:message>
  <wsdl:message name="GetSeatMapOutput"><wsdl:part name="parameters" element="tns:GetSeatMapResponse"/></wsdl:message>
  <wsdl:message name="CheckAvailabilityInput"><wsdl:part name="parameters" element="tns:CheckAvailabilityRequest"/></wsdl:message>
  <wsdl:message name="CheckAvailabilityOutput"><wsdl:part name="parameters" element="tns:CheckAvailabilityResponse"/></wsdl:message>
  <wsdl:message name="ReserveSeatsInput"><wsdl:part name="parameters" element="tns:ReserveSeatsRequest"/></wsdl:message>
  <wsdl:message name="ReserveSeatsOutput"><wsdl:part name="parameters" element="tns:ReserveSeatsResponse"/></wsdl:message>
  <wsdl:message name="GetReservationInput"><wsdl:part name="parameters" element="tns:GetReservationRequest"/></wsdl:message>
  <wsdl:message name="GetReservationOutput"><wsdl:part name="parameters" element="tns:GetReservationResponse"/></wsdl:message>
  <wsdl:message name="ExtendReservationInput"><wsdl:part name="parameters" element="tns:ExtendReservationRequest"/></wsdl:message>
  <wsdl:message name="ExtendReservationOutput"><wsdl:part name="parameters" element="tns:ExtendReservationResponse"/></wsdl:message>
  <wsdl:message name="ConfirmSeatsInput"><wsdl:part name="parameters" element="tns:ConfirmSeatsRequest"/></wsdl:message>
  <wsdl:message name="ConfirmSeatsOutput"><wsdl:part name="parameters" element="tns:ConfirmSeatsResponse"/></wsdl:message>
  <wsdl:message name="ReleaseSeatsInput"><wsdl:part name="parameters" element="tns:ReleaseSeatsRequest"/></wsdl:message>
  <wsdl:message name="ReleaseSeatsOutput"><wsdl:part name="parameters" element="tns:ReleaseSeatsResponse"/></wsdl:message>
  <wsdl:message name="ExpireReservationsInput"><wsdl:part name="parameters" element="tns:ExpireReservationsRequest"/></wsdl:message>
  <wsdl:message name="ExpireReservationsOutput"><wsdl:part name="parameters" element="tns:ExpireReservationsResponse"/></wsdl:message>
  <wsdl:message name="ConfigureInventoryInput"><wsdl:part name="parameters" element="tns:ConfigureInventoryRequest"/></wsdl:message>
  <wsdl:message name="ConfigureInventoryOutput"><wsdl:part name="parameters" element="tns:ConfigureInventoryResponse"/></wsdl:message>
  <wsdl:message name="SeatServiceFaultMessage"><wsdl:part name="fault" element="tns:SeatServiceFault"/></wsdl:message>
  <wsdl:portType name="SeatInventoryPortType">
    <wsdl:operation name="GetSeatMap"><wsdl:input message="tns:GetSeatMapInput"/><wsdl:output message="tns:GetSeatMapOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="CheckAvailability"><wsdl:input message="tns:CheckAvailabilityInput"/><wsdl:output message="tns:CheckAvailabilityOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="ReserveSeats"><wsdl:input message="tns:ReserveSeatsInput"/><wsdl:output message="tns:ReserveSeatsOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="GetReservation"><wsdl:input message="tns:GetReservationInput"/><wsdl:output message="tns:GetReservationOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="ExtendReservation"><wsdl:input message="tns:ExtendReservationInput"/><wsdl:output message="tns:ExtendReservationOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="ConfirmSeats"><wsdl:input message="tns:ConfirmSeatsInput"/><wsdl:output message="tns:ConfirmSeatsOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="ReleaseSeats"><wsdl:input message="tns:ReleaseSeatsInput"/><wsdl:output message="tns:ReleaseSeatsOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="ExpireReservations"><wsdl:input message="tns:ExpireReservationsInput"/><wsdl:output message="tns:ExpireReservationsOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
    <wsdl:operation name="ConfigureInventory"><wsdl:input message="tns:ConfigureInventoryInput"/><wsdl:output message="tns:ConfigureInventoryOutput"/><wsdl:fault name="SeatServiceFault" message="tns:SeatServiceFaultMessage"/></wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SeatInventorySoapBinding" type="tns:SeatInventoryPortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="GetSeatMap"><soap:operation soapAction="urn:event-ticketing:seat:v1/GetSeatMap"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="CheckAvailability"><soap:operation soapAction="urn:event-ticketing:seat:v1/CheckAvailability"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="ReserveSeats"><soap:operation soapAction="urn:event-ticketing:seat:v1/ReserveSeats"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="GetReservation"><soap:operation soapAction="urn:event-ticketing:seat:v1/GetReservation"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="ExtendReservation"><soap:operation soapAction="urn:event-ticketing:seat:v1/ExtendReservation"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="ConfirmSeats"><soap:operation soapAction="urn:event-ticketing:seat:v1/ConfirmSeats"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="ReleaseSeats"><soap:operation soapAction="urn:event-ticketing:seat:v1/ReleaseSeats"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="ExpireReservations"><soap:operation soapAction="urn:event-ticketing:seat:v1/ExpireReservations"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
    <wsdl:operation name="ConfigureInventory"><soap:operation soapAction="urn:event-ticketing:seat:v1/ConfigureInventory"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output><wsdl:fault name="SeatServiceFault"><soap:fault name="SeatServiceFault" use="literal"/></wsdl:fault></wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SeatInventoryService"><wsdl:port name="SeatInventoryPort" binding="tns:SeatInventorySoapBinding"><soap:address location="http://localhost:8003/soap"/></wsdl:port></wsdl:service>
</wsdl:definitions>
