"""Interface repository cho Event."""

from collections.abc import Iterable
from typing import Protocol

from app.domain.entities import Event


class EventRepository(Protocol):
    def add(self, event: Event) -> None: ...
    def get(self, event_id: str) -> Event | None: ...
    def update(self, event: Event) -> None: ...
    def list_all(self) -> Iterable[Event]: ...
    def next_id(self) -> str: ...
