"""Interface repository cho Event."""
from typing import Iterable, Optional, Protocol

from app.domain.entities import Event


class EventRepository(Protocol):
    def add(self, event: Event) -> None: ...
    def get(self, event_id: str) -> Optional[Event]: ...
    def update(self, event: Event) -> None: ...
    def list_all(self) -> Iterable[Event]: ...
    def next_id(self) -> str: ...
