"""Interface (Protocol) cho repository - domain/application chi biet interface
nay, khong biet du lieu thuc su luu o dau (in-memory hay PostgreSQL)."""
from typing import Iterable, Optional, Protocol

from app.domain.entities import Customer
from app.domain.enums import ConsentChannel


class CustomerRepository(Protocol):
    def add(self, customer: Customer) -> None: ...
    def get(self, customer_id: str) -> Optional[Customer]: ...
    def get_by_email(self, email: str) -> Optional[Customer]: ...
    def get_by_phone(self, phone: str) -> Optional[Customer]: ...
    def update(self, customer: Customer, *, expected_version: int) -> None: ...
    def list_all(self) -> Iterable[Customer]: ...
    def next_id(self) -> str: ...
    def set_consent(self, customer_id: str, channel: ConsentChannel, granted: bool) -> None: ...


class IdempotencyStore(Protocol):
    """Luu lai response cua 1 request theo Idempotency-Key, de request lap
    lai (do ESB/client retry) tra ve DUNG response cu thay vi xu ly lai tu
    dau - bat buoc cho POST/PUT/consents/deactivate theo contracts/openapi/
    customer-service.yaml (parameter IdempotencyKey, required: true)."""

    def get(self, key: str) -> Optional[tuple[int, dict]]: ...
    def save(self, key: str, status_code: int, body: dict) -> None: ...
