"""Interface (Protocol) cho repository - domain/application chi biet interface
nay, khong biet du lieu thuc su luu o dau (in-memory hay PostgreSQL)."""
from typing import Iterable, Optional, Protocol

from app.domain.entities import Customer


class CustomerRepository(Protocol):
    def add(self, customer: Customer) -> None: ...
    def get(self, customer_id: str) -> Optional[Customer]: ...
    def get_by_email(self, email: str) -> Optional[Customer]: ...
    def update(self, customer: Customer) -> None: ...
    def list_all(self) -> Iterable[Customer]: ...
    def next_id(self) -> str: ...
