"""Interface (Protocol) cho repository - domain/application chi biet interface
nay, khong biet du lieu thuc su luu o dau (in-memory hay PostgreSQL)."""

from collections.abc import Iterable
from typing import Protocol

from app.domain.entities import Customer, IdentityMapping


class CustomerRepository(Protocol):
    def add(self, customer: Customer) -> None: ...
    def get(self, customer_id: str) -> Customer | None: ...
    def get_by_email(self, email: str) -> Customer | None: ...
    def get_by_phone(self, phone: str) -> Customer | None: ...
    def update(self, customer: Customer) -> None: ...
    def list_all(self) -> Iterable[Customer]: ...
    def next_id(self) -> str: ...
    def save_consent(self, customer_id: str, channel: str, granted: bool) -> None: ...
    def get_identity_mapping(self, identity_subject: str) -> IdentityMapping | None: ...
    def get_identity_mapping_by_customer(
        self, customer_id: str
    ) -> IdentityMapping | None: ...
    def save_identity_mapping(self, mapping: IdentityMapping) -> None: ...
