"""Interface (Protocol) cho repository - domain/application chi biet
interface nay, khong biet du lieu thuc su luu o dau (in-memory hay
PostgreSQL)."""
from typing import Iterable, Optional, Protocol

from app.domain.entities import Delivery


class DeliveryRepository(Protocol):
    def add(self, delivery: Delivery) -> None: ...
    def get(self, delivery_id: str) -> Optional[Delivery]: ...
    def exists_by_correlation_id(self, correlation_id: str) -> bool: ...
    def list_all(self) -> Iterable[Delivery]: ...
    def next_id(self) -> str: ...
