"""Interface (Protocol) cho repository - domain/application chi biet
interface nay, khong biet du lieu thuc su luu o dau (in-memory hay
PostgreSQL)."""
from typing import Iterable, Optional, Protocol

from app.domain.entities import Delivery, DeliveryAttempt, InboundEvent, Template


class EventDeliveryRepository(Protocol):
    def event_exists(self, event_id: str) -> bool: ...
    def get_event(self, event_id: str) -> Optional[InboundEvent]: ...
    def add_event(self, event: InboundEvent) -> None: ...
    def add_delivery(self, delivery: Delivery) -> None: ...
    def get_delivery(self, delivery_id: str) -> Optional[Delivery]: ...
    def list_deliveries(self) -> Iterable[Delivery]: ...
    def update_delivery(self, delivery: Delivery) -> None: ...
    def add_attempt(self, attempt: DeliveryAttempt) -> None: ...
    def next_delivery_id(self) -> str: ...


class TemplateRepository(Protocol):
    def get(self, code: str) -> Optional[Template]: ...
    def save(self, template: Template) -> None: ...
