"""Stable domain enumerations."""

from enum import StrEnum


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class RoleName(StrEnum):
    CUSTOMER = "CUSTOMER"
    ADMIN = "ADMIN"
    CHECKIN_STAFF = "CHECKIN_STAFF"
    SERVICE = "SERVICE"


class RoleAction(StrEnum):
    ASSIGN = "ASSIGN"
    REVOKE = "REVOKE"


class AuditResult(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    NO_CHANGE = "NO_CHANGE"


class AuditAction(StrEnum):
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"
    REFRESH = "REFRESH"
    LOGOUT = "LOGOUT"
    ROLE_CHANGE = "ROLE_CHANGE"
    BOOTSTRAP_ADMIN = "BOOTSTRAP_ADMIN"


class AuditReason(StrEnum):
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    RATE_LIMITED = "RATE_LIMITED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"  # nosec B105
    REFRESH_TOKEN_REUSE_DETECTED = "REFRESH_TOKEN_REUSE_DETECTED"  # nosec B105
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    SELF_ADMIN_REVOKE_FORBIDDEN = "SELF_ADMIN_REVOKE_FORBIDDEN"


class SessionRevokeReason(StrEnum):
    ROTATED = "ROTATED"
    REUSE_DETECTED = "REUSE_DETECTED"
    EXPIRED = "EXPIRED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    LOGOUT = "LOGOUT"
